/** Chapter each character shipped in, keyed by the API's character id. */
const CHARACTER_DLC: Record<string, string> = {
  Dwight: '0',
  Meg: '1',
  Claudette: '2',
  Jake: '3',
  Nea: '4',
  Laurie: 'DLC2',
  Ace: 'DLC3',
  Bill: 'L4D',
  Feng: 'DLC4',
  Smoke: 'DLC5',
  Kate: 'Guam',
  Quentin: 'England',
  Eric: 'Finland',
  Adam: 'Haiti',
  Jeff: 'Kenya',
  Jane: 'Mali',
  Ash: 'Ash',
  Nancy: 'Qatar',
  Steve: 'Qatar',
  Yui: 'Sweden',
  Zarina: 'Ukraine',
  S22: 'Wales',
  S23: 'Yemen',
  S24: 'Aurora',
  S25: 'Comet',
  S26: 'Eclipse',
  S27: 'Eclipse',
  S28: 'Hubble',
  S29: 'Ion',
  S30: 'Kepler',
  S31: 'Meteor',
  S32: 'Orion',
  S33: 'Orion',
  S34: 'Quantum',
  S35: 'Saturn',
  S36: 'Saturn',
  S37: 'Umbra',
  S38: 'Venus',
  S39: 'Wormhole',
  S40: 'Zodiac',
  S41: 'ApplePie',
  S42: 'Churros',
  S43: 'Donut',
  S44: 'Eclair',
  S45: 'Gelato',
  S46: 'Jerky',
  S47: 'Lasagna',
  S48: 'Lasagna',
  S49: 'Maple',
  Chuckles: '268435456',
  Bob: '268435457',
  HillBilly: '268435458',
  Nurse: '268435459',
  Witch: 'DLC3',
  Shape: 'DLC2',
  Killer07: 'DLC4',
  Bear: 'DLC5',
  Cannibal: 'Cannibal',
  Nightmare: 'England',
  Pig: 'Finland',
  Clown: 'Guam',
  Spirit: 'Haiti',
  Legion: 'Kenya',
  Plague: 'Mali',
  Ghostface: 'Oman',
  Demogorgon: 'Qatar',
  Oni: 'Sweden',
  Gunslinger: 'Ukraine',
  K20: 'Wales',
  K21: 'Yemen',
  K22: 'Aurora',
  K23: 'Comet',
  K24: 'Eclipse',
  K25: 'Gemini',
  K26: 'Ion',
  K27: 'Kepler',
  K28: 'Meteor',
  K29: 'Orion',
  K30: 'Quantum',
  K31: 'Saturn',
  K32: 'Umbra',
  K33: 'Wormhole',
  K34: 'Yerkes',
  K35: 'ApplePie',
  K36: 'Churros',
  K37: 'Eclair',
  K38: 'Gelato',
  K39: 'Icecream',
  K40: 'Ketchup',
  K41: 'Maple',
}

/** How often each map is drawn, keyed by the API's map id. */
const MAP_DRAW_PERCENT: Record<string, string> = {
  Eng_Street_01: '4.55%',
  Ukr_Saloon: '4.55%',
  Sub_Street: '4.55%',
  Wal_Level_01: '4.55%',
  Wrm_Level_01: '4.55%',
  Fin_Hideout: '4.55%',
  Qat_Lab: '4.55%',
  Uba_Level_01: '4.55%',
  Hos_Treatment: '4.55%',
  Asy_Asylum: '2.05%',
  Ion_level_01: '2.05%',
  Hti_Manor: '2.05%',
  Asy_Chapel: '2.05%',
  Qtm_Level_02: '2.05%',
  Swp_GrimPantry: '2.05%',
  Brl_MaHouse: '2.05%',
  Kny_Cottage: '2.05%',
  Glo_Level_01: '2.05%',
  Ecl_Level_01: '2.05%',
  Ecl_Level_WestSide: '2.05%',
  Hti_Shrine: '2.05%',
  Swp_PaleRose: '2.05%',
  Qtm_Level_01: '2.05%',
  Brl_Temple: '2.05%',
  Apl_Shack: '1.59%',
  Apl_Level_02: '1.59%',
  Mtr_Level_1: '1.59%',
  Apl_Level_01: '1.59%',
  Ion_Shack: '1.43%',
  Jnk_Office: '1.37%',
  Jnk_Lodge: '1.37%',
  Ind_CoalTower: '1.37%',
  Frm_Barn: '1.37%',
  Jnk_GasStation: '1.37%',
  Ind_Storehouse: '1.37%',
  Ind_Foundry: '1.37%',
  Frm_Slaughterhouse: '1.37%',
  Frm_Cornfield: '1.37%',
  Ind_Forest: '1.37%',
  Ind_Mine: '1.37%',
  Frm_Farmhouse: '1.37%',
  Frm_Silo: '1.37%',
  Jnk_Scrapyard: '1.37%',
  Jnk_Garage: '1.37%',
}

export function characterMetaTags(id: string): string[] {
  const dlc = CHARACTER_DLC[id]
  return dlc ? [`DLC ${dlc}`] : []
}

export function mapMetaTags(id: string): string[] {
  const drawPercent = MAP_DRAW_PERCENT[id]
  return drawPercent ? [`Draw ${drawPercent}`] : []
}
